import { StyleSheet } from 'react-native';

export const darkColors = {
  background: '#050806',
  surface: '#101714',
  surfaceSoft: '#17231E',
  jade: '#00A86B',
  jadeDark: '#007A50',
  jadeSoft: '#123E31',
  text: '#F3FFF8',
  muted: '#91A39A',
  border: '#20382F',
  danger: '#FF6B6B',
  warning: '#F2B84B',
  warningSoft: '#3B2D13',
  splashBackground: '#F8FCF9',
};

export const lightColors = {
  background: '#F5FBF8',
  surface: '#FFFFFF',
  surfaceSoft: '#E8F5EF',
  jade: '#007A50',
  jadeDark: '#005C3D',
  jadeSoft: '#DCF4EA',
  text: '#082119',
  muted: '#5C7168',
  border: '#CDE4DA',
  danger: '#C84545',
  warning: '#966B00',
  warningSoft: '#FFF4D6',
  splashBackground: '#F8FCF9',
};

export const getThemeColors = (themeName) => (
  themeName === 'light' ? lightColors : darkColors
);

export const createGlobalStyles = (themeColors = darkColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: themeColors.background,
    padding: 20,
    paddingBottom: 84,
  },
  centeredContainer: {
    flex: 1,
    backgroundColor: themeColors.background,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  splashContainer: {
    flex: 1,
    backgroundColor: themeColors.splashBackground,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  splashImage: {
    width: '100%',
    height: '100%',
  },
  splashLoader: {
    bottom: 44,
    position: 'absolute',
  },
  splashPulse: {
    alignItems: 'center',
    height: 132,
    justifyContent: 'center',
    width: 132,
  },
  splashPulseLogo: {
    height: 132,
    width: 132,
  },
  splashTitle: {
    color: '#082119',
    fontSize: 22,
    fontWeight: '900',
    marginTop: 20,
    textAlign: 'center',
  },
  loadingText: {
    color: themeColors.muted,
    fontSize: 14,
    marginTop: 10,
    textAlign: 'center',
  },
  errorText: {
    color: themeColors.danger,
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  screenTitle: {
    color: themeColors.text,
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 6,
  },
  screenSubtitle: {
    color: themeColors.muted,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 22,
  },
  label: {
    color: themeColors.text,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
  },
  input: {
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    borderRadius: 8,
    padding: 15,
    marginBottom: 15,
    fontSize: 16,
    color: themeColors.text,
  },
  formKeyboardContainer: {
    flex: 1,
    backgroundColor: themeColors.background,
  },
  formScrollContent: {
    flexGrow: 1,
    padding: 20,
    paddingBottom: 96,
  },
  button: {
    backgroundColor: themeColors.jade,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
    elevation: 2,
  },
  buttonText: {
    color: themeColors.background,
    fontSize: 16,
    fontWeight: '800',
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  outlineButton: {
    borderWidth: 1,
    borderColor: themeColors.jade,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
  },
  outlineButtonText: {
    color: themeColors.jade,
    fontSize: 16,
    fontWeight: '800',
  },
  smallButton: {
    backgroundColor: themeColors.jadeSoft,
    borderColor: themeColors.jade,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  smallButtonText: {
    color: themeColors.text,
    fontSize: 12,
    fontWeight: '800',
  },
  dangerButton: {
    backgroundColor: themeColors.danger,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  dangerButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  totalCard: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderWidth: 1,
    padding: 14,
    borderRadius: 8,
    marginBottom: 10,
  },
  totalHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  totalHeaderActions: {
    flexDirection: 'row',
    gap: 8,
  },
  iconGhostButton: {
    alignItems: 'center',
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  totalLabel: {
    color: themeColors.muted,
    fontSize: 16,
  },
  totalValue: {
    color: themeColors.jade,
    fontSize: 30,
    fontWeight: '900',
    marginTop: 4,
  },
  totalHint: {
    color: themeColors.muted,
    fontSize: 13,
    marginTop: 8,
    lineHeight: 18,
  },
  gestureHint: {
    color: themeColors.muted,
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 10,
    marginTop: -2,
  },
  listLoadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    color: themeColors.muted,
    marginTop: 20,
    textAlign: 'center',
  },
  listItem: {
    backgroundColor: themeColors.surface,
    padding: 15,
    borderRadius: 8,
    marginBottom: 12,
    borderLeftWidth: 5,
    borderLeftColor: themeColors.jade,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: themeColors.border,
    borderRightColor: themeColors.border,
    borderBottomColor: themeColors.border,
  },
  itemTitleBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingRight: 12,
  },
  itemCategoryIcon: {
    alignItems: 'center',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  itemTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: 'bold',
    color: themeColors.text,
  },
  itemCategory: {
    fontSize: 14,
    color: themeColors.muted,
    marginTop: 4,
  },
  itemCategoryChip: {
    borderWidth: 1,
    borderRadius: 8,
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    gap: 12,
  },
  itemValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: themeColors.jade,
  },
  itemDate: {
    fontSize: 12,
    color: themeColors.muted,
  },
  statusPending: {
    backgroundColor: themeColors.warningSoft,
    color: themeColors.warning,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: '800',
  },
  statusPaid: {
    backgroundColor: themeColors.jadeSoft,
    color: themeColors.jade,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: '800',
  },
  brandContainer: {
    alignItems: 'center',
    gap: 2,
  },
  logoFrame: {
    width: 74,
    height: 74,
    borderRadius: 8,
    backgroundColor: 'transparent',
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoFrameLarge: {
    width: 118,
    height: 118,
    borderRadius: 8,
    backgroundColor: 'transparent',
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoImage: {
    width: 58,
    height: 58,
  },
  logoImageLarge: {
    width: 94,
    height: 94,
  },
  brandTitle: {
    color: themeColors.jade,
    fontSize: 24,
    fontWeight: '900',
    textAlign: 'center',
  },
  brandTitleLarge: {
    color: themeColors.jade,
    fontSize: 34,
    fontWeight: '900',
    textAlign: 'center',
  },
  brandSubtitle: {
    color: themeColors.text,
    fontSize: 14,
    fontWeight: '700',
    marginTop: -3,
    textAlign: 'center',
  },
  menuHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  headerLeftControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minWidth: 52,
  },
  headerMenuButton: {
    alignItems: 'center',
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  headerBackButton: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    width: 34,
  },
  hamburgerButton: {
    alignItems: 'center',
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    elevation: 4,
    height: 46,
    justifyContent: 'center',
    left: 14,
    position: 'absolute',
    top: 62,
    width: 46,
    zIndex: 50,
  },
  menuBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'flex-start',
  },
  menuPanel: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    marginLeft: 14,
    marginTop: 60,
    padding: 16,
    width: 280,
  },
  menuCloseButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    marginBottom: 14,
    width: 42,
  },
  menuPanelTitle: {
    color: themeColors.text,
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 12,
  },
  menuPanelItem: {
    alignItems: 'center',
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginBottom: 10,
    padding: 12,
  },
  menuPanelIcon: {
    alignItems: 'center',
    backgroundColor: themeColors.jadeSoft,
    borderRadius: 8,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  menuPanelText: {
    color: themeColors.text,
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  menuCard: {
    alignItems: 'center',
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    marginBottom: 14,
    padding: 16,
  },
  menuIcon: {
    color: themeColors.jade,
    fontSize: 15,
    fontWeight: '900',
    width: 56,
    textAlign: 'center',
  },
  menuTextBox: {
    flex: 1,
  },
  menuTitle: {
    color: themeColors.text,
    fontSize: 17,
    fontWeight: '900',
    marginBottom: 4,
  },
  menuDescription: {
    color: themeColors.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  startHeader: {
    alignItems: 'center',
    marginBottom: 14,
    marginTop: 0,
  },
  startIntroText: {
    color: themeColors.muted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 28,
    textAlign: 'left',
    width: '100%',
  },
  startActions: {
    gap: 14,
  },
  startCard: {
    alignItems: 'center',
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 92,
    padding: 16,
  },
  startCardIcon: {
    alignItems: 'center',
    backgroundColor: themeColors.jadeSoft,
    borderRadius: 8,
    height: 54,
    justifyContent: 'center',
    width: 54,
  },
  startCardTextBox: {
    flex: 1,
  },
  startCardTitle: {
    color: themeColors.text,
    fontSize: 17,
    fontWeight: '900',
    marginBottom: 5,
  },
  startCardDescription: {
    color: themeColors.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  homeFloatingButton: {
    alignItems: 'center',
    backgroundColor: themeColors.jade,
    borderColor: themeColors.jadeDark,
    borderRadius: 27,
    borderWidth: 1,
    bottom: 22,
    elevation: 5,
    height: 54,
    justifyContent: 'center',
    position: 'absolute',
    right: 20,
    width: 54,
    zIndex: 40,
  },
  themeSection: {
    marginTop: 10,
  },
  themeOptionsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  themeOption: {
    flex: 1,
    alignItems: 'center',
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 12,
    gap: 6,
  },
  themeOptionActive: {
    backgroundColor: themeColors.jadeSoft,
    borderColor: themeColors.jade,
  },
  themeOptionText: {
    color: themeColors.muted,
    fontSize: 13,
    fontWeight: '800',
  },
  themeOptionTextActive: {
    color: themeColors.jade,
  },
  settingsCard: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 8,
    padding: 16,
  },
  filterBlock: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 12,
    padding: 12,
  },
  filterBlockInline: {
    borderTopColor: themeColors.border,
    borderTopWidth: 1,
    marginTop: 12,
    paddingTop: 12,
  },
  filterTitle: {
    color: themeColors.text,
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 8,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  filterScrollContent: {
    gap: 8,
    paddingRight: 10,
  },
  filterChip: {
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  filterChipActive: {
    backgroundColor: themeColors.jadeSoft,
    borderColor: themeColors.jade,
  },
  filterChipText: {
    color: themeColors.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  filterChipTextActive: {
    color: themeColors.jade,
  },
  periodModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    justifyContent: 'center',
    padding: 20,
  },
  periodModalCard: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    maxHeight: '86%',
    padding: 16,
  },
  periodModalTitle: {
    color: themeColors.text,
    fontSize: 20,
    fontWeight: '900',
    marginBottom: 16,
  },
  periodModalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  monthGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 15,
  },
  monthOption: {
    alignItems: 'center',
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    minWidth: '30%',
    paddingHorizontal: 8,
    paddingVertical: 9,
  },
  swipeItemShell: {
    marginBottom: 0,
  },
  swipeActionsBack: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  swipeAction: {
    alignItems: 'center',
    borderRadius: 8,
    height: '86%',
    justifyContent: 'center',
    width: 78,
  },
  swipeEditAction: {
    backgroundColor: themeColors.jadeSoft,
  },
  swipeDeleteAction: {
    backgroundColor: themeColors.danger,
  },
  swipeItemFront: {
    backgroundColor: themeColors.background,
  },
  trashItem: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderLeftColor: themeColors.danger,
    borderLeftWidth: 5,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 12,
    padding: 15,
  },
  trashActions: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
    marginTop: 12,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 15,
  },
  categoryOption: {
    alignItems: 'center',
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 48,
    paddingHorizontal: 10,
    paddingVertical: 8,
    width: '48%',
  },
  categoryOptionActive: {
    backgroundColor: themeColors.surfaceSoft,
  },
  categoryOptionIcon: {
    alignItems: 'center',
    borderRadius: 8,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  categoryOptionText: {
    color: themeColors.muted,
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
  },
  onboardingContainer: {
    flex: 1,
    backgroundColor: themeColors.background,
    justifyContent: 'space-between',
    padding: 24,
  },
  onboardingCard: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderWidth: 1,
    borderRadius: 8,
    padding: 22,
  },
  onboardingCounter: {
    color: themeColors.jade,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  onboardingTitle: {
    color: themeColors.text,
    fontSize: 27,
    fontWeight: '900',
    marginBottom: 12,
  },
  onboardingText: {
    color: themeColors.muted,
    fontSize: 16,
    lineHeight: 24,
  },
  onboardingActions: {
    gap: 8,
  },
  dotsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 24,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: themeColors.border,
  },
  dotActive: {
    width: 24,
    height: 8,
    borderRadius: 4,
    backgroundColor: themeColors.jade,
  },
});

export const colors = darkColors;
export const globalStyles = createGlobalStyles(darkColors);
